version: '3.0'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cron_job:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command: cron -f
    depends_on:
      - "db"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "3000:3000"
    command: bundle exec rails s -b '0.0.0.0'
    depends_on:
      - "db"

volumes:
  pgdata:
